name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install the Rust toolchain
        run: rustup update stable && rustup default stable && rustup component add clippy rustfmt

      - name: Build
        run: cargo build --all-features --all-targets

      - name: Test
        run: cargo test --all-features

      - name: Test (no default features)
        run: cargo test --no-default-features

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Format
        run: cargo fmt --check
